### ISSUE TITLE
Some conjuncts lack anchor points

### ISSUE THREAD

**Issue by dscorbett** [notofonts/nandinagari#12]
### Font 
NotoSansNandinagari-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/nandinagari/releases/tag/NotoSansNandinagari-v1.002
Date: 2023-10-09

### Font version
Version 1.002

### Issue
Many conjunct glyphs are missing one or two anchor points. They should all have anchor points above and below.

<details>
<summary>Missing both anchor points</summary>

* `BaBa.Nnagari`
* `BaBa.Nnagari.ss03`
* `BaBaRa.Nnagari`
* `BaBaRa.Nnagari.ss03`
* `BaBha.Nnagari.ss03`
* `BaDha.Nnagari`
* `BaDha.Nnagari.ss03`
* `BaDhaVa.Nnagari`
* `BaDhaVa.Nnagari.ss03`
* `BaGa.Nnagari`
* `BaGa.Nnagari.ss03`
* `BaLa.Nnagari.ss03`
* `BaVa.Nnagari`
* `BaVa.Nnagari.ss03`
* `BhaRaVa.Nnagari.ss03`
* `DaDhaMa.Nnagari`
* `DaDhaMa.Nnagari.ss02`
* `DaDhaNa.Nnagari`
* `DaDhaRa.Nnagari.ss03`
* `DaDhaVa.Nnagari`
* `DhaVaRa.Nnagari.ss04`
* `GaBa.Nnagari`
* `GaBa.Nnagari.ss03`
* `GaBaRa.Nnagari`
* `GaBaRa.Nnagari.ss03`
* `GaBha.Nnagari`
* `GaBhaRa.Nnagari`
* `GaLa.Nnagari`
* `GaNa.Nnagari`
* `GaRaVa.Nnagari`
* `GaRaVa.Nnagari.ss03`
* `GaVa.Nnagari`
* `GaVaRa.Nnagari`
* `GaVaRa.Nnagari.ss03`
* `LaGa.Nnagari`
* `LaGaVa.Nnagari`
* `LlaGa.Nnagari`
* `LlaLla.Nnagari`
* `MaNa.Nnagari`
* `NaBa.Nnagari`
* `NaBa.Nnagari.ss03`
* `NaBaRa.Nnagari`
* `NaBaRa.Nnagari.ss03`
* `NaBha.Nnagari`
* `NaBhaRa.Nnagari`
* `NaBhaRa.Nnagari.ss03`
* `NaMaLa.Nnagari`
* `NaMaRa.Nnagari`
* `NaMaRa.Nnagari.ss03`
* `NaNaVa.Nnagari`
* `NaPaSa.Nnagari`
* `NaVa.Nnagari`
* `NaVaRa.Nnagari`
* `NaVaRa.Nnagari.ss03`
* `SsaNnaVa.Nnagari`
* `TaKaSsaMa.Nnagari.ss02`
* `TaRaVa.Nnagari.ss03`
* `ThaVa.Nnagari`
* `YaVa.Nnagari`
</details>

<details>
<summary>Missing an above-base anchor point</summary>

* `BaBha.Nnagari`
* `BaLa.Nnagari`
* `BaRa.Nnagari`
* `DaDhaRa.Nnagari`
* `DhaVa.Nnagari.ss01`
* `DhaVaRa.Nnagari.ss01`
* `GaDha.Nnagari.ss02`
* `JaMa.Nnagari`
* `JaMa.Nnagari.ss03`
* `LaRa.Nnagari`
* `LaRa.Nnagari.ss03`
* `MaBa.Nnagari`
* `MaBa.Nnagari.ss03`
* `MaBha.Nnagari`
* `MaLa.Nnagari`
* `MaVa.Nnagari`
* `NaNa.Nnagari`
* `NaTa.Nnagari`
* `SsaPaVa.Nnagari`
* `TaRaVa.Nnagari`
</details>

<details>
<summary>Missing a below-base anchor point</summary>

* `PaCaCha.Nnagari`
* `PaCaCha.Nnagari.ss01`
* `PaTaVa.Nnagari`
</details>

**Comment by simoncozens** [comment]
Thank you so much for the exhaustive list. Something seems to have gone wrong with anchor propagation in this font, even when I turned it on. I used mekkablue's "Shine through anchors" script to manually add the anchors to the conjuncts.
