### ISSUE TITLE
Conjuncts are not formed when - NA/GA/GHA are second members

### ISSUE THREAD

**Issue by sridatta1** [notofonts/nandinagari#15]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 

Some of the the conjuncts are broken and displayed with Virama
### Font 
Noto sans Nandinagari 
L

### Where the font came from, and when

https://fonts.google.com/noto/specimen/Noto+Sans+Nandinagari/tester
Tested here
On Google chrome
 
  >   Date: 2024-10-06 (preferred format)

### OS name and version
iOS 18

### Application name and version
Google chrome

### Issue
Some of the conjuncts are broken and displayed with Virama.
Even the second consonant is either ga, gha or na majorly.
This might be a technical issue rather than absence of glyphs as even Repha is not formed
  1. Steps to reproduce
  𑦰𑧠𑦰 𑦰𑧠𑦱 𑦰𑧠𑧁 𑧈𑧠𑦰 𑧈𑧠𑧁 𑧈𑧠𑦱 𑧍𑧠𑧁 𑧂𑧠𑧁 𑧁𑧠𑧁 𑦿𑧠𑦱
𑦲𑧠𑦰 𑦲𑧠𑦱 𑦽𑧠𑧁 Character data
  3. Observed results
  
![image](https://github.com/user-attachments/assets/011557cd-7dca-46f6-9dcf-ca37d9228650)
![image](https://github.com/user-attachments/assets/87feed5e-a22c-4124-a29f-82cc0cff950d)
![image](https://github.com/user-attachments/assets/7fd972e0-2990-4b51-b155-06f0572d2501)

  5. Expected results
  6. 
 conjuncts Should be formed

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

𑦰𑧠𑦰 𑦰𑧠𑦱 𑦰𑧠𑧁 𑧈𑧠𑦰 𑧈𑧠𑧁 𑧈𑧠𑦱 𑧍𑧠𑧁 𑧂𑧠𑧁 𑧁𑧠𑧁 𑦿𑧠𑦱
𑦲𑧠𑦰 𑦲𑧠𑦱 𑦽𑧠𑧁

### Screenshot
Added above
## More information 
The conjuncts tab can be used here for filtering and testing
https://www.aksharamukha.com/describe/Nandinagari
Would be helpful if these issues are fixed quickly

**Comment by simoncozens** [comment]
This is already fixed in the repo; I will cut 1.003 and onboard to Google Fonts.
