### ISSUE TITLE
repha is broken and spacing in some conjuncts with ba and ma

### ISSUE THREAD

**Issue by sridatta1** [notofonts/nandinagari#16]
### Title 
  > repha is broken and spacing in some conjuncts having ba and ma

### Font 
Noto Sans Nandinagari
### Where the font came from, and when
  > For example:

https://fonts.google.com/noto/specimen/Noto+Sans+Nandinagari
From here and tested there
  >   Date: 2024-10-06 (preferred format)

### OS name and version
iOS 18

### Application name and version
Chrome 

### Issue

  > repha is broken and spacing in some conjuncts having ba and ma

  1. Steps to reproduce

  Text 𑧈𑧠𑧆𑧠𑧊 𑧈𑧠𑧆𑧠𑧉 𑧈𑧠𑧆𑧠𑧄
𑧈𑧠𑧄 𑧈𑧠𑧄𑧠𑧄 𑧈𑧠𑧄𑧠𑧅 𑧈𑧠𑧄𑧠𑧈 𑧈𑧠𑧄𑧠𑧉 𑧈𑧠𑧄𑧠𑧊 𑧈𑧠𑧄𑧠𑧊 𑧈𑧠𑧄𑧠𑧀  𑧈𑧠𑦵𑧠𑧆

Transliteration: rmva rmla rmba
rba rbba rbbha rbra rbla rbva rbva rbdha  rjma
There may be more such conjuncts 
  3. Observed results
 
![image](https://github.com/user-attachments/assets/d88c82cd-fda6-4bc7-bbb1-d5631e69a67d)

  5. Expected results
Should be like
![image](https://github.com/user-attachments/assets/ccbf9347-0ea7-4829-acc9-542bee9d926f)

 

### Character data
  > given above 

### Screenshot
  > Mentioned above

**Comment by simoncozens** [comment]
This is fixed in the repository, but not on the version on Google Fonts. I need to make a new release.

**Comment by sridatta1** [comment]
Many thanks
