### ISSUE TITLE
Broken conjunct glyphs in version 1.002

### ISSUE THREAD

**Issue by dscorbett** [notofonts/nandinagari#6]
### Font 
NotoSansNandinagari-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/nandinagari/releases/tag/NotoSansNandinagari-v1.002
Date: 2023-10-09

### Font version
Version 1.002

### Issue
#4 was mostly fixed but some glyphs are still broken, now in different ways.

* `BaGa.Nnagari`
* `BaGa.Nnagari.ss03`
* `KaKaLa.Nnagari.ss02`
* `KaKaVa.Nnagari.ss02`
* `LaGa.Nnagari`
* `LlaGa.Nnagari`
* `TaKaLa.Nnagari.ss02`
* `TaKaRa.Nnagari`
* `TaKaRa.Nnagari.ss03`
* `TaKaTa.Nnagari`
* `TaKaVa.Nnagari.ss02`

**Comment by simoncozens** [comment]
The baga/laga/llaga problem was related to bad glyphs categories leading to some consonants not being placed into the `@AllLetters` glyph class. The other problem was https://github.com/googlefonts/glyphsLib/issues/948; I just decomposed the nested components because life is short.
